- name: Install zram
  ansible.builtin.package:
    name:
      - zram-tools
      - systemd-zram-generator
    state: present
  become: true
  register: zram_package_installed

- name: Add zram config
  ansible.builtin.copy:
    dest: "/etc/systemd/zram-generator.conf"
    content: |
      [zram0]
      zram-size = ram / 4
      compression-algorithm = zstd
    mode: u=rw,g=r,o=r
  become: true
  register: zram_config_updated

- name: Reload daemon configuration
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: zram_package_installed is changed or zram_config_updated is changed
  become: true

- name: Enable and start zram0
  ansible.builtin.service:
    name: systemd-zram-setup@zram0.service
    state: restarted
    enabled: true
  when: zram_package_installed is changed or zram_config_updated is changed
  become: true
