- name: Install samba
  ansible.builtin.package:
    name:
      - samba
      - smbclient
    state: present

- name: Configure smbd
  ansible.builtin.copy:
    dest: /etc/samba/smb.conf
    content: |
      [share]
      path = /mnt/share
      writeable = no
      browseable = yes
      public = yes
    mode: u=rw,g=r,o=r
  notify: Restart smbd

- name: Allow samba in ufw
  community.general.ufw:
    rule: allow
    name: Samba

- name: Enable and start smbd
  ansible.builtin.systemd_service:
    name: smbd
    state: started
    enabled: true

- name: Create users
  ansible.builtin.user:
    name: "{{ item.username }}"
    create_home: false
    shell: /usr/sbin/nologin
  loop: "{{ samba_users }}"
  no_log: true

- name: Create samba users
  ansible.builtin.shell: >
    set -e -o pipefail
    && (pdbedit --user='{{ item.username }}' 2>&1 > /dev/null)
    || (echo '{{ item.password }}'; echo '{{ item.password }}')
    | smbpasswd -s -a '{{ item.username }}'
  args:
    executable: /bin/bash
  register: samba_create_users
  changed_when: "'Added user' in samba_create_users.stdout"
  loop: "{{ samba_users }}"
  no_log: true

- name: Set samba passwords
  ansible.builtin.shell: >
    set -e -o pipefail
    && (smbclient -U '{{ item.username }}'%'{{ item.password }}' -L 127.0.0.1 2>&1 > /dev/null)
    || (echo '{{ item.password }}'; echo '{{ item.password }}')
    | smbpasswd '{{ item.username }}'
  args:
    executable: /bin/bash
  register: samba_verify_users
  changed_when: "'New SMB password' in samba_verify_users.stdout"
  loop: "{{ samba_users }}"
  no_log: true
