- name: Install pulseaudio
  ansible.builtin.package:
    name:
      - pulseaudio
      - pulseaudio-module-bluetooth
    state: present
  become: true

- name: Create autologin directory
  ansible.builtin.file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Add autologin
  ansible.builtin.copy:
    dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=-/sbin/agetty --autologin "{{ user }}" --noclear %I $TERM
    mode: u=rw,g=r,o=r
  become: true
  register: bluetooth_autologin

- name: Restart after adding autologin
  ansible.builtin.reboot:
  become: true
  when: bluetooth_autologin is changed # noqa: no-handler

- name: Edit bluetooth configuration file to allow discoverability
  ansible.builtin.lineinfile:
    path: /etc/bluetooth/main.conf
    regexp: 'DiscoverableTimeout ='
    line: DiscoverableTimeout = 0
  notify: Restart bluetooth
  become: true

- name: Edit bluetooth configuration file to change class
  ansible.builtin.lineinfile:
    path: /etc/bluetooth/main.conf
    regexp: 'Class ='
    line: Class = 0x41C
  notify: Restart bluetooth
  become: true

- name: Enable and start pulseaudio
  ansible.builtin.systemd_service:
    name: pulseaudio
    state: started
    enabled: true
    scope: user
  become: true
  become_user: "{{ user }}"

- name: Get bluetooth status
  ansible.builtin.command: bluetoothctl show
  changed_when: false
  register: bluetooth_status
  become: true
  become_user: "{{ user }}"

- name: Set bluetooth discoverable
  ansible.builtin.command: bluetoothctl discoverable on
  when: "'Discoverable: no' in bluetooth_status.stdout"
  changed_when: true
  check_mode: false
  become: true
  become_user: "{{ user }}"
