- name: Install snapclient
  ansible.builtin.package:
    name: snapclient
    state: present

- name: Edit configuration file
  ansible.builtin.lineinfile:
    path: /etc/default/snapclient
    regexp: '^SNAPCLIENT_OPTS='
    line: SNAPCLIENT_OPTS="--host {{ snapclient_host }}"
  notify: Restart snapclient

- name: Enable and start snapclient
  ansible.builtin.systemd_service:
    name: snapclient
    state: started
    enabled: true
