- name: Install mopidy
  ansible.builtin.package:
    name:
      - mopidy
      - mopidy-local
      - mopidy-mpd
      - mopidy-doc
      - python3-pip
      - python3-standard-imghdr
    state: present
  become: true

- name: Install Mopidy-Iris python package
  ansible.builtin.pip:
    name: Mopidy-Iris
    break_system_packages: true
  become: true

- name: Add configuration file
  ansible.builtin.copy:
    dest: /etc/mopidy/mopidy.conf
    content: |
      [core]
      restore_state = true

      [local]
      enabled = true
      media_dir = /mnt/share/Music
      scan_timeout = 10000

      [file]
      enabled = false

      [audio]
      output = pulsesink server=127.0.0.1

      [http]
      enabled = true
      hostname = 0.0.0.0
      port = 6680
      allowed_origins = {{ mopidy_allowed_origin }}

      [stream]
      enabled = false

    mode: u=rw,g=r,o=r
  notify: Restart mopidy
  become: true

- name: Create pulseaudio mopidy config
  ansible.builtin.copy:
    dest: /etc/pulse/default.pa.d/mopidy.pa
    content: |
      load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1
    mode: u=rw,g=r,o=r
  notify: Restart pulseaudio
  become: true

- name: Allow mopidy in ufw
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  become: true
  loop:
    - 6680

- name: Enable and start mopidy
  ansible.builtin.systemd_service:
    name: mopidy
    state: started
    enabled: true
  become: true
