---
- name: Configures all rpis
  tags: common
  hosts: kitchen_pi,tv_pi
  tasks:
    - name: Configure ssh authorized keys
      ansible.posix.authorized_key:
        user: "{{ user }}"
        exclusive: true
        key: "{{ ssh_authorized_keys | join('\n') }}"
      when: ssh_authorized_keys != None and ssh_authorized_keys | length > 0
    - name: Remove dphys-swapfile
      ansible.builtin.package:
        name: dphys-swapfile
        state: absent
      become: true
    - name: Create sysctl directory
      ansible.builtin.file:
        path: /etc/sysctl.d
        state: directory
        mode: u=rwx,g=rx,o=rx
      become: true
    - name: Set sysctl
      ansible.posix.sysctl:
        sysctl_file: /etc/sysctl.d/rpi.conf
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
      loop: "{{ sysctl_vars }}"
      become: true
    - name: Install ufw
      ansible.builtin.package:
        name: ufw
        state: present
      become: true
    - name: Allow ssh
      community.general.ufw:
        rule: allow
        name: OpenSSH
      become: true
    - name: Enable UFW
      community.general.ufw:
        state: enabled
      become: true

- name: Configures kitchen pi
  tags: common
  hosts: kitchen_pi
  tasks:
    - name: Mount NAS drive
      ansible.posix.mount:
        path: /mnt/share
        src: UUID=394bcd8a-281d-4c0b-ad20-00e1d06844af
        fstype: ext4
        state: mounted
        passno: 2
      become: true
    - name: Disable wifi
      ansible.builtin.lineinfile:
        path: /boot/firmware/config.txt
        regexp: 'dtoverlay=disable-wifi'
        line: dtoverlay=disable-wifi
      notify: Restart
      become: true
    - name: Disable bluetooth
      ansible.builtin.lineinfile:
        path: /boot/firmware/config.txt
        regexp: 'dtoverlay=disable-bt'
        line: dtoverlay=disable-bt
      notify: Restart
      become: true
  handlers:
    - name: Restart
      ansible.builtin.reboot:
      become: true

- name: Configures tv pi
  tags: common
  hosts: tv_pi
  tasks:
    - name: Mount samba share
      ansible.posix.mount:
        path: /mnt/share
        src: //kitchen-pi.local/share
        fstype: cifs
        state: mounted
        opts: guest,_netdev,x-systemd.automount
      become: true
    - name: Disable wifi
      ansible.builtin.lineinfile:
        path: /boot/firmware/config.txt
        regexp: 'dtoverlay=disable-wifi'
        line: dtoverlay=disable-wifi
      notify: Restart
      become: true
  handlers:
    - name: Restart
      ansible.builtin.reboot:
      become: true

- name: Configures all rpis roles
  tags: roles
  hosts: kitchen_pi,tv_pi
  roles:
    - snapclient
    - zram
    - log2ram

- name: Configures kitchen_pi roles
  tags: roles
  hosts: kitchen_pi
  roles:
    - samba

- name: Configures tv_pi roles
  tags: roles
  hosts: tv_pi
  roles:
    - bluetooth
    - snapserver
    - mopidy
